### PR TITLE
Fixes a "NoMethodError: private method `warn' called for nil:NilClass" error

### PR DESCRIPTION
**Pull request by rymai**
Thanks for the gem!

I've also fixed the tests, updated the Rakefile, added Bundler & Guard and bump the version to 0.1.1.

**Edit:** I've also replaced Jeweler by a static .gemspec so I can reference my fork in my Gemfile.

Hope everything is good! ;)

Thanks!

### CODE REVIEW

**Comment by rymai** [comment]
@ashirazi Any chance to get this merged? :)

**Comment by ashirazi** [comment]
Sorry for taking so long to getting around to checking out the request.

Thanks for the improvements... it needed the update!

**Comment by rymai** [comment]
Cool, thank you very much! Could you release the 0.1.1 soon?

**Comment by ashirazi** [comment]
Had to make some updates to get code-coverage running again.

0.1.1 now released

thanks again

**Comment by rymai** [comment]
Thank you very much!!

**Pull request merged**
